<?php

return [
    'adminEmail' => 'admin@example.com',
    'apiUrl' => 'http://lr-eb-api-dev.elasticbeanstalk.com/api/',
    'companyName' => 'LendRise ScoreRise',
    'pageSize' => 20,
    'languages' => [
        'en' => 'EN',
        'ro' => 'RO',
    ],
    'currency' => 'RON',
    'coins' => [
        ['suma' => '1.99', 'coin' => 1, 'text' => '1 coin (1.99 RON)'],
        ['suma' => '3.99', 'coin' => 3, 'text' => '3 coin (3.99 RON)'],
        ['suma' => '5.99', 'coin' => 5, 'text' => '5 coin (5.99 RON)'],
        ['suma' => '9.99', 'coin' => 9, 'text' => '9 coin (9.99 RON)'],
    ],
    'lendRiseSite' => 'http://www.lendrise.com/',
    'mobilPay' => [
        #for testing purposes, all payment requests will be sent to the sandbox server.
        #Once your account will be active you must switch back to the live server https://secure.mobilpay.ro
        #in order to display the payment form in a different language, simply add the language identifier to the
        #end of the paymentUrl, i.e https://secure.mobilpay.ro/en for English
        #$paymentUrl => 'https://secure.mobilpay.ro';
        'paymentUrl' => 'http://sandboxsecure.mobilpay.ro',

        #this is the path on your server to the public certificate.
        #You may download this from Admin -> Conturi de comerciant -> Detalii -> Setari securitate
        'x509FilePath' => __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'components' . DIRECTORY_SEPARATOR . 'mobilPay' . DIRECTORY_SEPARATOR . 'certificates' . DIRECTORY_SEPARATOR . 'public.cer',
        #merchant account signature - generated by mobilpay.ro for every merchant account
        #semnatura contului de comerciant - mergi pe www.mobilpay.ro
        #Admin -> Conturi de comerciant -> Detalii -> Setari securitate
        'signature' => 'XXXX-XXXX-XXXX-XXXX-XXXX',
        #below is where mobilPay will send the payment result. This URL will always be called first; mandatory
        'confirmUrl' => 'http://app.customsoft.ro/lendrise-scorerise-web/web/site/mobil-pay-confirm',
        #below is where mobilPay redirects the client once the payment process is finished.
        #Not to be mistaken for a "successURL" nor "cancelURL"; mandatory
        'returnUrl' => 'http://app.customsoft.ro/lendrise-scorerise-web/web/site/mobil-pay-return',
        #calea catre cheia privata
        #cheia privata este generata de mobilpay, accesibil in Admin -> Conturi de comerciant -> Detalii -> Setari securitate
        'privateKeyFilePath' => __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'components' . DIRECTORY_SEPARATOR . 'mobilPay' . DIRECTORY_SEPARATOR . 'certificates' . DIRECTORY_SEPARATOR . 'private.key',
    ],
];
